name = "bam-cms-auth"
main = "src/index.js"
compatibility_date = "2026-06-03"
workers_dev = true
preview_urls = false

[vars]
ALLOWED_DOMAINS = "bammedia.us,www.bammedia.us"
GITHUB_SCOPE = "public_repo"
CMS_REDIRECT_URL = "https://bammedia.us/admin/"
